//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoESAN.Models.dbContext_SISEDUTIVA_PROD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SisEdutiva_prodEntities : DbContext
    {
        public SisEdutiva_prodEntities()
            : base("name=SisEdutiva_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PromocionZoomdle> PromocionZoomdle { get; set; }
    
        public virtual ObjectResult<SP_BUSCAR_ALUMNO_Result> SP_BUSCAR_ALUMNO(string buscar)
        {
            var buscarParameter = buscar != null ?
                new ObjectParameter("Buscar", buscar) :
                new ObjectParameter("Buscar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSCAR_ALUMNO_Result>("SP_BUSCAR_ALUMNO", buscarParameter);
        }
    
        public virtual ObjectResult<SP_BUSCAR_CURSO_Result> SP_BUSCAR_CURSO(Nullable<int> idActor)
        {
            var idActorParameter = idActor.HasValue ?
                new ObjectParameter("IdActor", idActor) :
                new ObjectParameter("IdActor", typeof(int));
                return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSCAR_CURSO_Result>("SP_BUSCAR_CURSO", idActorParameter);
        }
    
        public virtual ObjectResult<SP_CambiarEsPlanta_Result> SP_CambiarEsPlanta(Nullable<int> idActor)
        {
            var idActorParameter = idActor.HasValue ?
                new ObjectParameter("IdActor", idActor) :
                new ObjectParameter("IdActor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CambiarEsPlanta_Result>("SP_CambiarEsPlanta", idActorParameter);
        }
    
        public virtual ObjectResult<SP_CambiarEsPlantaListar_Result> SP_CambiarEsPlantaListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CambiarEsPlantaListar_Result>("SP_CambiarEsPlantaListar");
        }
    }
}
