//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoESAN.Models.dbContext_SISEDUTIVA_PROD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionZoomdle
    {
        public string PromocionCodigo { get; set; }
        public string Estado { get; set; }
        public int ID { get; set; }
    }
}
